/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "Board": "游戏板",
    "Buy": "购买",
    "Buy amount:": "购买数量：",
    "Cells": "单元格",
    "for": "",
    "Help": "帮助",
    "Hi! Welcome to progressive mine sweeper.": "你好！ 欢迎来到渐进式扫雷游戏。",
    "Hint": "提示",
    "MAX": "最大",
    "Minefield": "雷区",
    "Mines": "地雷",
    "next >": "下一个 >",
    "Progress": "进度",
    "Progressive Mine Sweep": "渐进式扫雷",
    "Reset": "重置",
    "Revealing": "揭示",
    "skip >>>": "跳过 >>>",
    "Tap mode:": "点按模式：",
    "The first part of this tutorial will walk you through how to play minesweeper. At any point in tutorial you can move to the next or previous pages. Feel free to skip to the next chapter if you already know how to play!": "本教程的第一部分将引导您了解如何玩扫雷。 在教程的任何时候，您都可以移至下一页或上一页。 如果您已经知道如何玩，请随意跳到下一章！",
    "the Game": "游戏",
    "This is my special take on the classic minesweeper game with progressive / incremental aspects built into it.": "这是我对经典扫雷游戏的特别看法，其中内置了渐进/增量方面。",
    "Win": "赢",
    "Wins": "获胜",
    "The game board consists of a playing field shaped like a grid of squares. There are a certain number of mines buried under this field. The objective of each game is to successfully clear all the empty cells, and flag the cells containing mines without triggering (exploding) them.": "游戏板由一个形状像方格的运动场组成。 这块地底下埋有一定数量的地雷。 每个游戏的目标是成功清除所有空单元格，并标记包含地雷的单元格而不触发（爆炸）它们。",
    "Clicking or tapping on an empty square will reveal its contents. The contents of a square is either clear or a mine. When revealing a clear square, you are given a clue to the number of mines surrounding it — in all directions, including diagonals. Revealing a mine, however, would trigger it and explode!": "单击或点击空白方块将显示其内容。 方块的内容要么是透明的，要么是地雷。 当显示一个清晰的正方形时，你会得到一个关于它周围的地雷数量的线索——在所有方向上，包括对角线。 然而，暴露地雷会触发它并爆炸！",
    "  in the middle means there's one mine hidden under one of the remaining squares around the centerpiece! Better be careful with this one...": "在中间意味着有一个地雷隐藏在围绕中心的剩余方块之一下！最好小心这个...",
    "  tells us there are no mines in the squares surrounding it, so it's safe to go ahead and reveal the 3 surrounding squares as well!": "  告诉我们在它周围的方格中没有地雷，所以继续并显示周围的 3 个方格是安全的！",
    "< back": "<返回",
    "Be careful with this one. Right (or meta) click on the square to flag it, or simply toggle the tapping mode to flag squares instead of revealing:": "小心这个。右键（或元）单击方块以标记它，或者简单地将点击模式切换为标记方块而不是显示：",
    "Flagging squares": "标记方块",
    "However, we know from the other 2 squares we just revealed that there are no mines in the 2 squares immediately surrounding those places.": "但是，我们从刚刚透露的其他 2 个方格中得知，紧邻这些地方的 2 个方格中没有地雷。",
    "In either case, you will be presented with an option to reset the board and receive a brand new game to play. We can upgrade this box and its functions later on.": "在任何一种情况下，您都会看到一个选项来重置棋盘并获得一个全新的游戏来玩。我们可以稍后升级这个盒子和它的功能。",
    "No sweat if you accidentally set off the mine in the previous step.": "如果您在上一步中不小心引爆了地雷，也不会出汗。",
    "Once you reveal all the squares and flag all the mines correctly, you win the playing field, and the game announces it to you.": "一旦你展示了所有的方块并正确地标记了所有的地雷，你就赢得了比赛场地，游戏会向你宣布。",
    "Reasoning about squares": "关于正方形的推理",
    "Revealing a square": "显示一个正方形",
    "Revealing squares": "显示方块",
    "Sample 3x3 board:": "样品 3x3 板：",
    "Similarly, if you set off a mine, you lose the playing field and need to reset the board.": "同样，如果您引爆了地雷，您将失去竞争环境并且需要重置棋盘。",
    "The revealed contents of  ": "揭露的内容",
    "This brings us to the final square in the corner which is obviously a mine! You won't want to set this off!": "这将我们带到角落的最后一个广场，这显然是一个地雷！你不会想要关闭它！",
    "Try clicking (or tapping) the hinted square below:": "尝试单击（或点击）下面的提示方块：",
    "Try clicking (or tapping) the hinted squares below:": "尝试单击（或点击）下面的提示方块：",
    "Uh oh! The  ": "哦哦！这",
    "What is minesweeper": "什么是扫雷",
    "Winning a game": "赢得一场比赛",
    "Cell": "单元格",
    "Game over!": "游戏结束！",
    "Rave ruined": "狂欢结束了",
    "You may reset the board to receive a brand new game to play:": "您可以重置游戏板以接收一个全新的游戏来玩：",
    "lost": "输了",
    "Flagging": "标记",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)\%$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);